// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_500 from "./routes/_500.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_notes_id_ from "./routes/api/notes/[id].ts";
import * as $api_notes_index from "./routes/api/notes/index.ts";
import * as $index from "./routes/index.tsx";
import * as $view_id_ from "./routes/view/[id].tsx";
import * as $AllNotes from "./islands/AllNotes.tsx";
import * as $NewNote from "./islands/NewNote.tsx";
import * as $NoteShow from "./islands/NoteShow.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_500.tsx": $_500,
    "./routes/_app.tsx": $_app,
    "./routes/api/notes/[id].ts": $api_notes_id_,
    "./routes/api/notes/index.ts": $api_notes_index,
    "./routes/index.tsx": $index,
    "./routes/view/[id].tsx": $view_id_,
  },
  islands: {
    "./islands/AllNotes.tsx": $AllNotes,
    "./islands/NewNote.tsx": $NewNote,
    "./islands/NoteShow.tsx": $NoteShow,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
